name: test

on:
  pull_request:
    branches: develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install sbt
      uses: coursier/setup-action@v1
      with:
        jvm: openjdk:17
        apps: sbtn
    
    - name: Test
      run: sbt test